import test from 'node:test';
import assert from 'node:assert/strict';
import {blankState,applyMutation,buildEvent,balance,totals,classification,cents,today,dateAdd,id,occurrenceDate,occurrences,forecast,DomainError,validDate} from '../shared/domain';
import {demoState} from '../server/seed';
import {reportData} from '../shared/reports';
import type {State,Mutation} from '../shared/types';
export function fixture(){const s=blankState(),now=new Date().toISOString();for(const [key,type,opening] of [['checking','CHECKING',100000],['savings','SAVINGS',50000],['wallet','WALLET',1000],['card','CREDIT_CARD',-50000],['loan','LOAN',-100000]] as any[])s.accounts.push({id:key,type,name:key,opening,trackingStart:'2024-01-01',archived:false,everUsed:false,order:s.accounts.length,institution:'',details:{},version:1,createdAt:now,updatedAt:now});for(const k of ['payees','categories'] as const)s[k].push({id:k,name:k,active:true,version:1,createdAt:now,updatedAt:now});return s;}
export function mutation(s:State,collection:Mutation['collection'],action:string,data:any,entityId=id()):Mutation{return {id:id(),epoch:s.epoch,collection,action,data,entityId,deviceId:'test',baseVersion:collection==='settings'?s.settings.version||0:s[collection].find(e=>e.id===entityId)?.version};}
const expense={type:'EXPENSE',date:'2026-01-15',accountId:'checking',amount:10000,payeeId:'payees',categoryId:'categories'};
function post(s:State,d:any){return applyMutation(s,mutation(s,'events','create',d));}
test('integer cents reject precision loss and malformed dates',()=>{assert.equal(cents('$1,234.56'),123456);assert.equal(cents('-0.01'),-1);for(const v of ['1.001','NaN','Infinity','1e4'])assert.throws(()=>cents(v));for(const d of ['2026-02-30','2026-13-01','garbage'])assert.equal(validDate(d),false);});
test('seed has the approved three funds/five debt accounts and exact derived totals',()=>{const s=demoState();assert.equal(s.accounts.length,8);assert.deepEqual(totals(s),{funds:1245000,debt:-2485000});});
test('all financial types have exact ledger effects and reporting classification',()=>{let s=fixture();const cases=[
 [expense,[['checking',-10000]],{income:0,spent:10000}],
 [{...expense,type:'INCOME'},[['checking',10000]],{income:10000,spent:0}],
 [{...expense,type:'TRANSFER',toAccountId:'savings'},[['checking',-10000],['savings',10000]],{income:0,spent:0}],
 [{...expense,type:'DEBT_PAYMENT',toAccountId:'card'},[['checking',-10000],['card',10000]],{income:0,spent:0}],
 [{...expense,type:'DEBT_PAYMENT',toAccountId:'loan',principal:8000,interest:2000},[['checking',-10000],['loan',8000]],{income:0,spent:10000}],
 [{...expense,type:'ADJUSTMENT',direction:1},[['checking',10000]],{income:10000,spent:0}],
 [{...expense,type:'ADJUSTMENT',direction:-1},[['checking',-10000]],{income:0,spent:10000}]
 ];for(const [d,entries,report] of cases as any[]){const e=buildEvent(s,d);assert.deepEqual(e.entries.map(l=>[l.accountId,l.amount]),entries);assert.deepEqual(classification(e),report);}
 const transferred=post(s,{...expense,type:'TRANSFER',toAccountId:'savings'});assert.equal(totals(transferred).funds,totals(s).funds);assert.equal(balance(transferred,'checking'),90000);assert.equal(balance(transferred,'savings'),60000);
});
test('invalid linked operations leave the input state untouched',()=>{const s=fixture(),before=structuredClone(s);for(const d of [{...expense,type:'TRANSFER',toAccountId:'checking'},{...expense,type:'TRANSFER',toAccountId:'card'},{...expense,type:'DEBT_PAYMENT',toAccountId:'loan',principal:9000,interest:2000},{...expense,date:dateAdd(today(),1)},{...expense,date:'2023-12-31'},{...expense,amount:1.5}])assert.throws(()=>post(s,d));assert.deepEqual(s,before);});
test('edit, void, restore affect both sides atomically and preserve revisions',()=>{let s=post(fixture(),{...expense,type:'TRANSFER',toAccountId:'savings'});let e=s.events[0];s=applyMutation(s,mutation(s,'events','update',{...e,amount:20000},e.id));assert.equal(balance(s,'savings'),70000);s=applyMutation(s,mutation(s,'events','void',{},e.id));assert.equal(balance(s,'checking'),100000);assert.equal(balance(s,'savings'),50000);s=applyMutation(s,mutation(s,'events','restore',{},e.id));assert.equal(balance(s,'savings'),70000);assert.equal(s.revisions.length,4);assert.equal(s.events.length,1);});
test('refund limits, dates and original void protection',()=>{let s=post(fixture(),expense),original=s.events[0];s=post(s,{...expense,type:'REFUND',refundOf:original.id,amount:6000,accountId:'card'});assert.equal(balance(s,'card'),-44000);assert.deepEqual(classification(s.events[1]),{income:6000,spent:0});assert.throws(()=>post(s,{...expense,type:'REFUND',refundOf:original.id,amount:4001}));assert.throws(()=>post(s,{...expense,type:'REFUND',refundOf:original.id,date:'2026-01-14',amount:100}));assert.throws(()=>applyMutation(s,mutation(s,'events','void',{},original.id)));assert.throws(()=>applyMutation(s,mutation(s,'events','update',{...original,amount:5999},original.id)));});
test('opening balance remains locked after void, labels retain snapshots',()=>{let s=post(fixture(),expense),e=s.events[0];s=applyMutation(s,mutation(s,'events','void',{},e.id));assert.throws(()=>applyMutation(s,mutation(s,'accounts','update',{opening:99999},'checking')));s=applyMutation(s,mutation(s,'payees','update',{name:'Renamed',active:true},'payees'));assert.equal(s.events[0].payee,'payees');assert.throws(()=>applyMutation(s,mutation(s,'payees','delete',{},'payees')));});
test('stale versions conflict for records and settings',()=>{let s=fixture();const first=mutation(s,'accounts','update',{name:'First'},'checking'),second=mutation(s,'accounts','update',{name:'Second'},'checking');s=applyMutation(s,first);assert.throws(()=>applyMutation(s,second),(e:DomainError)=>e.status===409);const a=mutation(s,'settings','update',{...s.settings,timeout:10},'settings'),b=mutation(s,'settings','update',{...s.settings,timeout:15},'settings');s=applyMutation(s,a);assert.throws(()=>applyMutation(s,b),(e:DomainError)=>e.status===409);});
test('month-end and leap-day recurrence return to the original day',()=>{const r={start:'2024-01-31',unit:'months',interval:1} as any;assert.deepEqual([0,1,2,3].map(i=>occurrenceDate(r,i)),['2024-01-31','2024-02-29','2024-03-31','2024-04-30']);assert.equal(occurrenceDate({...r,start:'2024-02-29',unit:'years'},1),'2025-02-28');assert.equal(occurrenceDate({...r,start:'2024-02-29',unit:'years'},4),'2028-02-29');});
test('finite schedules, skipped rows, overdue-first forecast and variable uncertainty',()=>{let s=fixture();s.settings.forecastTarget='date';s.settings.forecastDate=dateAdd(today(),5);const r={label:'Finite expense',start:dateAdd(today(),-2),unit:'days',interval:2,count:4,mode:'FIXED',status:'ACTIVE',template:expense,notifyDays:2,autoSplit:false};s=applyMutation(s,mutation(s,'rules','create',r,'rule'));assert.equal(occurrences(s).length,4);s=applyMutation(s,mutation(s,'occurrences','create',{ruleId:'rule',sequence:1,due:today(),status:'SKIPPED'},'rule:1'));s=applyMutation(s,mutation(s,'rules','create',{...r,label:'Unknown',mode:'VARIABLE',count:1,template:{...expense,amount:undefined}},'variable'));const f=forecast(s);assert.equal(f.value,121000);assert.equal(f.incomplete,true);assert.equal(f.rows[1].overdue,true);assert.equal(f.rows.filter(r=>r.id==='rule:1').length,0);});
test('future series splits retain posted occurrence identity and audit history',()=>{let s=fixture();const r={label:'Monthly',start:'2026-01-15',unit:'months',interval:1,count:4,mode:'FIXED',status:'ACTIVE',template:expense,notifyDays:2,autoSplit:false};s=applyMutation(s,mutation(s,'rules','create',r,'rule'));s=post(s,{...expense,occurrenceId:'rule:0'});const m=mutation(s,'rules','update',{...s.rules[0],start:'2026-02-15',splitFrom:'2026-02-15',count:3,template:{...expense,amount:12000}},'rule');s=applyMutation(s,m);assert.equal(s.rules.length,2);assert.equal(s.events[0].occurrenceId,'rule:0');assert.equal(s.events[0].amount,10000);assert.equal(occurrences(s).filter(o=>o.due==='2026-02-15').length,1);assert.equal(occurrences(s).find(o=>o.due==='2026-02-15').template.amount,12000);});
test('archiving blocks active schedules, archived activity stays reportable',()=>{let s=post(fixture(),expense);s=applyMutation(s,mutation(s,'accounts','update',{archived:true},'checking'));assert.equal(totals(s).funds,51000);assert.equal(reportData(s,{kind:'cashflow'}).rows[1].value,10000);assert.throws(()=>post(s,expense));});
test('balance history differs from net worth and matches every day’s derived balance',()=>{let s=post(fixture(),expense);const from='2026-01-14',to='2026-01-16';const funds=reportData(s,{kind:'balance',from,to}),net=reportData(s,{kind:'networth',from,to});assert.deepEqual(funds.rows.map(r=>r.value),[151000,141000,141000]);assert.deepEqual(net.rows.map(r=>r.value),[1000,-9000,-9000]);assert.deepEqual(reportData(s,{kind:'balance',account:'card',from,to}).rows.map(r=>r.value),[-50000,-50000,-50000]);});
test('reconciliation decisions preserve the ledger and completed sessions are read-only',()=>{let s=fixture();const before=totals(s);s=applyMutation(s,mutation(s,'reconciliations','create',{accountId:'checking',attachmentId:'fixture',status:'OPEN',items:[{id:'row',amount:-10000,status:'UNMATCHED'}]},'reconcile'));s=applyMutation(s,mutation(s,'reconciliations','update',{...s.reconciliations[0],status:'COMPLETE'},'reconcile'));assert.deepEqual(totals(s),before);assert.throws(()=>applyMutation(s,mutation(s,'reconciliations','update',{status:'OPEN'},'reconcile')),/read-only/);});
