import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';import {resolve,join} from 'node:path';import {Store,hash} from '../server/store';import {createApp} from '../server/index';import {blankState,buildEvent,id,totals,today,dateAdd} from '../shared/domain';import {demoState} from '../server/seed';import AdmZip from 'adm-zip';import {parseCSV,matchItems,reportPDF,pdfText,parseStatementText,ocrImage} from '../server/documents';import PDFDocument from 'pdfkit';
function temp(){const root=resolve('test-results');mkdirSync(root,{recursive:true});return mkdtempSync(join(root,'integration-'));}
function mut(s:any,collection:string,data:any,entityId=id(),action='create',baseVersion?:number){return {id:id(),epoch:s.epoch,collection,action,entityId,baseVersion,data,deviceId:'integration'} as any;}
test('API setup, CSRF, auth, atomic writes, idempotency, conflicts, session expiry',async()=>{const store=new Store(temp());const {app}=await createApp(store);try{
 assert.equal((await app.inject('/api/v1/state')).statusCode,401);
 assert.equal((await app.inject({method:'POST',url:'/api/v1/setup',payload:{}})).statusCode,403);
 const setup=await app.inject({method:'POST',url:'/api/v1/setup',headers:{'x-requested-with':'balancebook'},payload:{email:'test@example.com',password:'TestOwner2026!',demo:true}});assert.equal(setup.statusCode,200,setup.body);let s=setup.json().state;const token=setup.cookies[0].value,headers={'x-requested-with':'balancebook',cookie:'bb_session='+token};
 assert.equal((await app.inject({method:'POST',url:'/api/v1/setup',headers,payload:{email:'other@example.com',password:'AnotherOwner!'}})).statusCode,400);
 const checking=s.accounts.find(a=>a.type==='CHECKING'),savings=s.accounts.find(a=>a.type==='SAVINGS');const m=mut(s,'events',{type:'TRANSFER',date:today(),accountId:checking.id,toAccountId:savings.id,amount:12345});
 const result=await app.inject({method:'POST',url:'/api/v1/mutations',headers,payload:m});assert.equal(result.statusCode,200,result.body);assert.equal((await app.inject({method:'POST',url:'/api/v1/mutations',headers,payload:m})).body,result.body);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM ledger_entries WHERE event_id=?').get(m.entityId).n,2);assert.deepEqual(totals(store.state()),totals(s));
 const previous=store.state().events.length;const invalid=mut(s,'events',{...m.data,toAccountId:checking.id});assert.equal((await app.inject({method:'POST',url:'/api/v1/mutations',headers,payload:invalid})).statusCode,400);assert.equal(store.state().events.length,previous);
 const edit=mut(s,'events',{...m.data,amount:10000},m.entityId,'update',1);assert.equal((await app.inject({method:'POST',url:'/api/v1/mutations',headers,payload:edit})).statusCode,200);const stale={...edit,id:id()};assert.equal((await app.inject({method:'POST',url:'/api/v1/mutations',headers,payload:stale})).statusCode,409);assert.equal(store.state().events.find(e=>e.id===m.entityId).amount,10000);
 assert.throws(()=>store.db.prepare("DELETE FROM revisions").run(),/immutable/);
 const resolution=await app.inject({method:'POST',url:'/api/v1/conflict-resolution',headers,payload:{entityId:m.entityId,collection:'events',local:stale.data}});assert.equal(resolution.statusCode,200);assert.equal(store.state().revisions.at(-1).action,'resolve-conflict-keep-server');assert.equal(store.state().events.find(e=>e.id===m.entityId).amount,10000);
 assert.equal((await app.inject({method:'POST',url:'/api/v1/backup',headers:{...headers,origin:'https://attacker.example'},payload:{}})).statusCode,403);
 store.db.prepare('UPDATE sessions SET last_seen=?').run(Date.now()-31*60000);assert.equal((await app.inject({url:'/api/v1/state',headers})).statusCode,401);
 }finally{await app.close();store.close();}});
test('scheduler posts fixed occurrences once, waits for variable and unapproved splits, ends finite series',async()=>{const store=new Store(temp());let s=demoState();s.rules=[];s.events=s.events.filter(e=>!e.occurrenceId);store.save(s);store.setMeta('owner',{email:'test@example.com',password:'test-only'});const checking=s.accounts.find(a=>a.type==='CHECKING');const template={type:'EXPENSE',accountId:checking.id,amount:1000,payeeId:s.payees[0].id,categoryId:s.categories[0].id};const rule={label:'Due',start:today(),unit:'weeks',interval:2,count:1,mode:'FIXED',status:'ACTIVE',template,notifyDays:2,autoSplit:false};store.mutate(mut(s,'rules',rule,'due'));store.mutate(mut(s,'rules',{...rule,mode:'VARIABLE',template:{...template,amount:undefined}},'variable'));const {app,tick}=await createApp(store);try{const before=store.state().events.length;await tick();await tick();assert.equal(store.state().events.length,before+1);assert.equal(store.state().rules.find(r=>r.id==='due').status,'ENDED');assert.equal(store.state().rules.find(r=>r.id==='variable').status,'ACTIVE');assert.equal(store.state().events.filter(e=>e.occurrenceId==='due:0').length,1);}finally{await app.close();store.close();}});
test('backup round-trip into a clean install preserves balances, attachments, audit and rejects corrupt archives',()=>{const store=new Store(temp());const s=demoState();store.save(s);store.setMeta('owner',{email:'restore@example.com',password:'hashed-test-owner'});const file=Buffer.from('sample attachment'),filename=hash(file)+'.csv';writeFileSync(join(store.dir,'files',filename),file);const b=store.backup(),bytes=readFileSync(join(store.dir,'backups',b.filename));const clean=new Store(temp());try{clean.restore(bytes);assert.deepEqual(totals(clean.state()),totals(s));assert.equal(clean.state().events.length,s.events.length);assert.equal(clean.state().revisions.length,s.revisions.length);assert.equal(readFileSync(join(clean.dir,'files',filename)).toString(),'sample attachment');assert.notEqual(clean.state().epoch,s.epoch);assert.equal(clean.meta('owner').email,'restore@example.com');assert.equal(clean.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');const zip=new AdmZip(bytes);zip.updateFile('database.sqlite',Buffer.from('corrupt'));assert.throws(()=>clean.restore(zip.toBuffer()),/checksum/);assert.deepEqual(totals(clean.state()),totals(s));}finally{store.close();clean.close();}});
test('CSV/PDF parsing and matching are review-only; all five report PDFs contain exact figures',async()=>{const s=demoState(),e=s.events.find(e=>e.type==='EXPENSE'&&e.status==='ACTIVE'),aid=e.accountId;const csv=`Date,Description,Debit,Credit\n${e.date},${e.payee},${e.amount/100},\ninvalid,Bad,10,\n`;const parsed=parseCSV(csv);assert.equal(parsed.items.length,1);assert.equal(parsed.issues.length,1);assert.equal(parsed.items[0].amount,-e.amount);const before=JSON.stringify(s),matched=matchItems(s,aid,parsed.items);assert.equal(matched[0].suggestions[0].id,e.id);assert.equal(matched[0].status,'UNMATCHED');assert.equal(JSON.stringify(s),before);
 for(const kind of ['category','payee','cashflow','balance','networth']){const pdf=await reportPDF(s,{kind,from:dateAdd(today(),-3),to:today()});assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.match(await pdfText(pdf),/Exact figures/);}
 const d=new PDFDocument(),chunks:Buffer[]=[];const done=new Promise<Buffer>(r=>{d.on('data',b=>chunks.push(b));d.on('end',()=>r(Buffer.concat(chunks)))});d.text('Statement test fixture - reference only').text(`${e.date} ${e.payee} -${(e.amount/100).toFixed(2)}`).text('Please review all suggestions before approving a ledger change.');d.end();const rows=parseStatementText(await pdfText(await done));assert.equal(rows.length,1);assert.equal(rows[0].amount,-e.amount);
});
test('local receipt OCR returns an editable suggestion without posting',async()=>{const {createCanvas}=await import('@napi-rs/canvas');const c=createCanvas(1000,400),ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1000,400);ctx.fillStyle='black';ctx.font='44px Arial';ctx.fillText('DEMO MARKET',50,80);ctx.fillText('09/05/2026',50,150);ctx.fillText('TOTAL 42.50',50,240);const result=await ocrImage(c.toBuffer('image/png'));assert.match(result.text,/42[.,]50/);assert.equal(result.total,'42.50');});
