import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {blankState,applyMutation,balance,id} from '../shared/domain';
import {Store} from '../server/store';
import {adjustmentFor} from '../src/ReviewActions';
function setup(){let s=blankState();const now=new Date().toISOString();s.accounts.push({id:'a',name:'Test',type:'CHECKING',opening:100000,trackingStart:'2020-01-01',archived:false,everUsed:false,order:0,institution:'',details:{},version:1,createdAt:now,updatedAt:now});
 s=applyMutation(s,{id:id(),epoch:s.epoch,collection:'events',action:'create',entityId:'adjust',deviceId:'test',data:{type:'ADJUSTMENT',direction:-1,date:'2026-08-28',accountId:'a',amount:5648}});
 s=applyMutation(s,{id:id(),epoch:s.epoch,collection:'reconciliations',action:'create',entityId:'review',deviceId:'test',data:{accountId:'a',status:'OPEN',items:[{id:'one',amount:-1926,date:'2026-08-24',description:'Amazon',sourceId:'bank-one',status:'UNMATCHED'},{id:'two',amount:-3722,date:'2026-08-24',description:'Other',sourceId:'bank-two',status:'UNMATCHED'}]}});return s;}
const operation=(s:any,rowId='one')=>({id:id(),epoch:s.epoch,collection:'reconciliations' as const,action:'replace-adjustment',entityId:'review',baseVersion:s.reconciliations[0].version,deviceId:'test',data:{rowId,adjustmentId:'adjust',adjustmentVersion:s.events.find(e=>e.id==='adjust').version,payee:'Amazon',category:'Shopping'}});
test('partial and final replacement preserve balance, match rows, and retain audit history',()=>{let s=setup();const initial=balance(s,'a'),snapshot=JSON.stringify(s),m=operation(s);s=applyMutation(s,m);assert.equal(balance(s,'a'),initial);assert.equal(s.events.find(e=>e.id==='adjust').amount,3722);assert.equal(s.reconciliations[0].items[0].status,'LINKED');assert.equal(s.events.find(e=>e.id===m.id+':expense').amount,1926);assert.equal(adjustmentFor(s,s.reconciliations[0],s.reconciliations[0].items[1])?.id,'adjust');assert.notEqual(JSON.stringify(s),snapshot);s=applyMutation(s,operation(s,'two'));assert.equal(balance(s,'a'),initial);assert.equal(s.events.find(e=>e.id==='adjust').status,'VOIDED');assert.equal(s.payees.length,1);assert.ok(s.revisions.some(r=>r.entityId==='adjust'&&r.action==='void'));});
test('stale adjustments, overdraws, handled rows and invalid purchases fail without changing state',()=>{const s=setup(),before=JSON.stringify(s);for(const data of [{adjustmentVersion:0},{rowId:'missing'},{category:''}]){const m=operation(s);assert.throws(()=>applyMutation(s,{...m,data:{...m.data,...data}}));assert.equal(JSON.stringify(s),before);}const oversized=structuredClone(s);oversized.reconciliations[0].items[0].amount=-99999;assert.throws(()=>applyMutation(oversized,operation(oversized)),/exceeds/);const done=applyMutation(s,operation(s));assert.throws(()=>applyMutation(done,operation(done)),/unresolved/);});
test('SQLite mutation retries are idempotent and failed operations roll back labels and ledger',()=>{const store=new Store(mkdtempSync(join(tmpdir(),'bb-replace-')));try{store.save(setup());const m=operation(store.state());store.mutate(m);const result=store.state();store.mutate(m);assert.deepEqual(store.state(),result);const fail=operation(result,'two');fail.data.category='';assert.throws(()=>store.mutate(fail));assert.deepEqual(store.state(),result);}finally{store.close()}});
