import PDFDocument from 'pdfkit';
import Papa from 'papaparse';
import {PDFParse} from 'pdf-parse';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
import type {State} from '../shared/types';
import {balance,classification,dateAdd,DomainError,money,cents,validDate,id} from '../shared/domain';
import {reportData} from '../shared/reports';
export {reportRows,reportData} from '../shared/reports';
export async function reportPDF(s:State,filter:any){const {rows,events}=reportData(s,filter);const chunks:Buffer[]=[];const doc=new PDFDocument({size:'LETTER',margin:44,bufferPages:true});const done=new Promise<Buffer>(resolve=>{doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));});const titles={category:'Spending by category',payee:'Spending by payee',cashflow:'Income versus Spent',balance:'Balance over time',networth:'Net worth over time'};doc.fontSize(20).text('Balancebook');doc.fontSize(15).text(titles[filter.kind]||titles.category);doc.moveDown(.5).fontSize(9).fillColor('#444').text(`Dates: ${filter.from||'All'} to ${filter.to||'Today'} | Generated ${new Date().toISOString()}`).text(`Account: ${s.accounts.find(a=>a.id===filter.account)?.name||(filter.kind==='balance'?'Available Funds / active funds accounts':filter.kind==='networth'?'All active accounts':'All (including archived)')}`).text(`Category: ${s.categories.find(a=>a.id===filter.category)?.name||'All'} | Payee: ${s.payees.find(a=>a.id===filter.payee)?.name||'All'}`);doc.moveDown();
 const chart=rows.length>24?rows.filter((_,i)=>i%Math.ceil(rows.length/24)===0):rows;const max=Math.max(1,...chart.map(r=>Math.abs(r.value)));for(const r of chart.slice(0,24)){if(doc.y>670)doc.addPage();const y=doc.y;doc.fontSize(8).fillColor('#222').text(r.label,44,y,{width:130});doc.rect(180,y,Math.abs(r.value)/max*230,9).fill(r.value<0?'#b75551':'#326e95');doc.fillColor('#222').text(money(r.value),425,y,{width:95,align:'right'});doc.y=y+18;}doc.moveDown().fontSize(12).text('Exact figures');for(const r of rows){if(doc.y>690)doc.addPage();doc.fontSize(9).text(`${r.label}    ${money(r.value)}`);}doc.moveDown().fontSize(10).text(`${events.length} matching active transactions. Opening balances excluded from activity metrics.`);const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.fontSize(8).text(`Page ${i+1} of ${range.count}`,44,740,{lineBreak:false});}doc.end();return done;}
export function parseCSV(text:string,mapping:any={}){const parsed=Papa.parse<any>(text,{header:true,skipEmptyLines:true});const headers=parsed.meta.fields||[];const find=(names:string[])=>headers.find(h=>names.includes(h.toLowerCase().trim()));const columns={date:mapping.date||find(['date','transaction date','posted date']),description:mapping.description||find(['description','payee','merchant','name']),amount:mapping.amount||find(['amount','total']),debit:mapping.debit||find(['debit','withdrawal']),credit:mapping.credit||find(['credit','deposit'])};const issues:string[]=[];const items=parsed.data.map((r:any,index:number)=>{try{let d=String(r[columns.date]||'').trim();if(!validDate(d)){const parts=d.split(/[/-]/);if(parts.length===3){const [x,y,z]=parts;d=`${z.length===2?'20'+z:z}-${(mapping.dateFormat==='DMY'?y:x).padStart(2,'0')}-${(mapping.dateFormat==='DMY'?x:y).padStart(2,'0')}`;}}if(!validDate(d))throw new Error('date');const amount=columns.amount?cents(String(r[columns.amount]).replace(/^\((.*)\)$/,'-$1')):cents(String(r[columns.credit]||'0'))-Math.abs(cents(String(r[columns.debit]||'0')));return {id:id(),date:d,description:String(r[columns.description]||''),amount,status:'UNMATCHED'};}catch{issues.push(`Row ${index+2}: check date/amount mapping.`);return null}}).filter(Boolean);return {headers,columns,items,issues,preview:parsed.data.slice(0,5)};}
export function matchItems(s:State,accountId:string,items:any[],tolerance=3){return items.map(item=>{const candidates=s.events.filter(e=>e.status==='ACTIVE'&&e.entries.some(l=>l.accountId===accountId&&l.amount===item.amount)&&Math.abs(new Date(e.date).getTime()-new Date(item.date).getTime())<=tolerance*86400000);const tokens=(x:string)=>x.toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).filter(Boolean);const scored=candidates.map(e=>({id:e.id,score:(e.date===item.date?60:35)+(tokens(e.payee).some(w=>tokens(item.description).includes(w))?40:0)})).sort((a,b)=>b.score-a.score);return {...item,suggestions:scored.slice(0,3),match:scored.length>1?'Possible duplicate':scored[0]?.score>=60?'Strong match':scored.length?'Possible match':'Missing from ledger'};});}
export async function ocrImage(buffer:Buffer){const {createWorker}=await import('tesseract.js');const req=createRequire(import.meta.url);const language=req.resolve('@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz');const worker=await createWorker('eng',1,{langPath:resolve(language,'..'),gzip:true,cacheMethod:'none'});try{const {data}=await worker.recognize(buffer);const lines=data.text.split('\n').map(l=>l.trim()).filter(Boolean);const total=lines.find(l=>/\btotal\b/i.test(l)&&/\d/.test(l));return {text:data.text,payee:lines[0]||'',total:total?.match(/\d+[.,]\d{2}/)?.[0]?.replace(',','.')||'',date:lines.find(l=>/\d{1,2}[/-]\d{1,2}[/-]\d{2,4}/.test(l))?.match(/\d{1,2}[/-]\d{1,2}[/-]\d{2,4}/)?.[0]||'',confidence:data.confidence};}finally{await worker.terminate();}}
export async function pdfText(buffer:Buffer){const parser=new PDFParse({data:buffer});try{let result=(await parser.getText()).text;if(result.trim().length<50){const pages=await parser.getScreenshot({first:10,scale:1.5});result='';for(const p of pages.pages)result+=(await ocrImage(Buffer.from(p.data))).text+'\n';}return result;}finally{await parser.destroy();}}
export function parseStatementText(text:string){const items=[];for(const line of text.split('\n')){const m=line.match(/(\d{4}-\d{2}-\d{2}|\d{1,2}\/\d{1,2}\/\d{4})\s+(.+?)\s+(-?\$?[\d,]+\.\d{2})(?:\s|$)/);if(!m)continue;let date=m[1];if(date.includes('/')){const [mm,dd,yy]=date.split('/');date=`${yy}-${mm.padStart(2,'0')}-${dd.padStart(2,'0')}`;}if(validDate(date))items.push({id:id(),date,description:m[2],amount:cents(m[3]),status:'UNMATCHED'});}return items;}
