import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import multipart from '@fastify/multipart';
import staticFiles from '@fastify/static';
import rateLimit from '@fastify/rate-limit';
import argon2 from 'argon2';
import {randomBytes} from 'node:crypto';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join,resolve,basename,extname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {z} from 'zod';
import {Store,hash} from './store';
import {demoState} from './seed';
import {DomainError,blankState,id,occurrences,today,applyMutation,assert,dateAdd} from '../shared/domain';
import {reportPDF,parseCSV,parseStatementText,pdfText,matchItems,ocrImage} from './documents';

import {copyCloudBackups} from './cloud';
export async function createApp(store=new Store()){
 const app=Fastify({logger:{level:'warn',redact:['req.headers.cookie','req.headers.authorization','body']},bodyLimit:3*1024*1024,trustProxy:process.env.TRUST_PROXY==='true'});
 await app.register(cookie);await app.register(multipart,{limits:{fileSize:25*1024*1024,files:1}});await app.register(rateLimit,{global:false});
 const authSchema=z.object({email:z.email().max(200),password:z.string().min(10).max(200),demo:z.boolean().optional()});
 const mutationSchema=z.object({id:z.string().min(8).max(100),epoch:z.string().max(100),collection:z.enum(['accounts','events','categories','payees','rules','occurrences','settings','reconciliations','checkpoints']),action:z.enum(['create','update','void','restore','delete','replace-adjustment','match-split']),entityId:z.string().min(1).max(160),baseVersion:z.number().int().optional(),data:z.record(z.string(),z.any()),deviceId:z.string().max(100),resolution:z.string().max(100).optional()});
 app.setErrorHandler((e:any,req,reply)=>{const status=e instanceof DomainError?e.status:e instanceof z.ZodError?400:e.statusCode||500;if(status>=500)app.log.error({code:e.code||e.name},'Operation failed');reply.code(status).send({error:status>=500?'The operation could not be completed. Your existing data is preserved.':e instanceof z.ZodError?e.issues.map(i=>i.message).join(' '):e.message,details:e.details||null});});
 const setSession=(reply:any)=>{const token=randomBytes(32).toString('hex');store.db.prepare('INSERT INTO sessions VALUES(?,?)').run(hash(token),Date.now());reply.setCookie('bb_session',token,{httpOnly:true,sameSite:'strict',secure:process.env.APP_ORIGIN?.startsWith('https://')||false,path:'/',maxAge:7*86400});};
 app.addHook('onSend',async(req,reply,payload)=>{if(String(reply.getHeader('content-type')).includes('text/html'))reply.header('Cache-Control','no-store');return payload;});
 app.addHook('onRequest',async(req:any,reply)=>{
  reply.header('X-Content-Type-Options','nosniff').header('Referrer-Policy','same-origin').header('X-Frame-Options','DENY').header('Content-Security-Policy',`default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self'; frame-src 'none'; worker-src 'self' blob:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'`);
  if(!req.url.startsWith('/api/'))return;
  reply.header('Cache-Control','no-store');
  if(!['GET','HEAD'].includes(req.method)){if(req.headers['x-requested-with']!=='balancebook')throw new DomainError('Missing request verification.',403);const origin=req.headers.origin;if(origin&&origin!==(process.env.APP_ORIGIN||`${req.protocol}://${req.headers.host}`))throw new DomainError('Untrusted request origin.',403);}
  if(['/api/v1/status','/api/v1/login','/api/v1/setup','/api/health'].includes(req.url.split('?')[0]))return;
  const token=req.cookies.bb_session;const row:any=token&&store.db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(hash(token));const timeout=store.meta('settings').timeout*60000;
  if(!row||Date.now()-row.last_seen>timeout){if(token)store.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token));throw new DomainError('Please log in again.',401);}store.db.prepare('UPDATE sessions SET last_seen=? WHERE token_hash=?').run(Date.now(),hash(token));
 });
 app.get('/api/health',()=>({status:'ok',version:'1.0.0-demo'}));
 app.get('/api/v1/status',()=>({initialized:!!store.meta('owner'),version:'1.0.0-demo'}));
 app.post('/api/v1/setup',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req,reply)=>{const d=authSchema.parse(req.body);assert(!store.meta('owner'),'Owner setup is already complete.');const password=await argon2.hash(d.password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1});store.transaction(()=>{assert(!store.meta('owner'),'Owner setup is already complete.');const s=d.demo?demoState():blankState();if(!d.demo){const now=new Date().toISOString();for(const name of ['Groceries','Transport','Salary','Dining','Utilities','Health','Housing','Other'])s.categories.push({id:id(),version:1,createdAt:now,updatedAt:now,name,active:true});}store.save(s);store.setMeta('owner',{email:d.email.toLowerCase(),password});});setSession(reply);store.backup();return {email:d.email,state:store.state()};});
 app.post('/api/v1/login',{config:{rateLimit:{max:8,timeWindow:'5 minutes'}}},async(req,reply)=>{const d=authSchema.parse(req.body),owner=store.meta('owner');if(!owner||owner.email!==d.email.toLowerCase()||!await argon2.verify(owner.password,d.password))throw new DomainError('Email or password is incorrect.',401);setSession(reply);return {email:owner.email,state:store.state()};});
 app.post('/api/v1/logout',(req,reply)=>{if(req.cookies.bb_session)store.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(req.cookies.bb_session));reply.clearCookie('bb_session',{path:'/'});return {ok:true};});
 app.post('/api/v1/password',async(req:any)=>{const owner=store.meta('owner');assert(await argon2.verify(owner.password,String(req.body.current||'')),'Current password is incorrect.');const password=z.string().min(10).max(200).parse(req.body.password);store.setMeta('owner',{...owner,password:await argon2.hash(password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1})});store.db.exec('DELETE FROM sessions');return {ok:true};});
 app.get('/api/v1/state',()=>({state:store.state(),backups:store.db.prepare('SELECT * FROM backups ORDER BY created_at DESC LIMIT 30').all(),backupError:store.meta('lastBackupError'),email:store.meta('owner').email}));
 app.post('/api/v1/mutations',(req)=>store.mutate(mutationSchema.parse(req.body) as any));
 app.post('/api/v1/conflict-resolution',(req:any)=>{const d=z.object({entityId:z.string().max(160),collection:z.enum(['accounts','events','categories','payees','rules','occurrences','settings','reconciliations','checkpoints']),local:z.record(z.string(),z.any())}).parse(req.body);store.transaction(()=>{const s=store.state(),server=d.collection==='settings'?s.settings:s[d.collection].find(e=>e.id===d.entityId);s.revisions.push({id:id(),entityId:d.entityId,entityType:d.collection,action:'resolve-conflict-keep-server',before:d.local,after:server||null,at:new Date().toISOString(),actor:'owner'});store.save(s)});return {ok:true}});
 app.post('/api/v1/backup',()=>store.backup());
 app.get('/api/v1/backups/:id',async(req:any,reply)=>{const row:any=store.db.prepare('SELECT * FROM backups WHERE id=?').get(req.params.id);assert(row,'Backup not found.');return reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename="${basename(row.filename)}"`).send(readFileSync(join(store.dir,'backups',basename(row.filename))));});
 app.post('/api/v1/restore',async(req,reply)=>{const part=await req.file({limits:{fileSize:250*1024*1024}});assert(part,'Choose a backup ZIP file.');const data=await part.toBuffer();const confirm=(part.fields.confirm as any)?.value;assert(confirm==='RESTORE','Type RESTORE to confirm replacement.');const result=store.restore(data);reply.clearCookie('bb_session',{path:'/'});return result;});
 app.get('/api/v1/report',async(req:any,reply)=>reply.type('application/pdf').header('Content-Disposition','attachment; filename="balancebook-report.pdf"').send(await reportPDF(store.state(),req.query)));
 app.post('/api/v1/files',async(req)=>{const part=await req.file();assert(part,'Choose a file.');const buffer=await part.toBuffer();const fileExt=extname(part.filename).toLowerCase();const mime=buffer.subarray(0,4).toString()==='%PDF'?'application/pdf':buffer[0]===137&&buffer[1]===80?'image/png':buffer[0]===255&&buffer[1]===216?'image/jpeg':fileExt==='.csv'?'text/csv':null;assert(mime,'Supported files: PDF, CSV, PNG, JPEG.');const entityId=String((part.fields.entityId as any)?.value||'');const kind=(part.fields.kind as any)?.value==='statement'?'statement':'transaction';assert(kind==='statement'||store.state().events.some(e=>e.id===entityId),'Save the transaction before attaching files.');const digest=hash(buffer),diskName=digest+(mime==='application/pdf'?'.pdf':mime==='image/png'?'.png':mime==='image/jpeg'?'.jpg':'.csv');writeFileSync(join(store.dir,'files',diskName),buffer,{mode:0o600});const clientId=String((part.fields.clientId as any)?.value||'');if(clientId){const prior=store.state().attachments.find(a=>(a as any).clientId===clientId);if(prior)return prior;}const now=new Date().toISOString(),a={id:id(),clientId,version:1,createdAt:now,updatedAt:now,filename:basename(part.filename).slice(0,200),mime,size:buffer.length,hash:digest,entityId,kind,diskName};store.transaction(()=>{const s=store.state();s.attachments.push(a as any);store.save(s);});return a;});
 app.get('/api/v1/files/:id',async(req:any,reply)=>{const a:any=store.state().attachments.find(a=>a.id===req.params.id);assert(a,'Attachment not found.');return reply.type(a.mime).header('Content-Disposition',`attachment; filename="${a.filename.replace(/["\r\n]/g,'')}"`).send(readFileSync(join(store.dir,'files',basename(a.diskName))));});
 app.post('/api/v1/files/:id/ocr',async(req:any)=>{const a:any=store.state().attachments.find(a=>a.id===req.params.id);assert(a,'Attachment not found.');const buffer=readFileSync(join(store.dir,'files',basename(a.diskName)));const result=a.mime==='application/pdf'?{text:await pdfText(buffer),confidence:0}:await ocrImage(buffer);store.transaction(()=>{const s=store.state();s.attachments.find(v=>v.id===a.id).ocr=result;store.save(s);});return result;});
 app.post('/api/v1/parse-statement',async(req:any)=>{const a:any=store.state().attachments.find(a=>a.id===req.body.attachmentId);assert(a,'Statement file not found.');const buffer=readFileSync(join(store.dir,'files',basename(a.diskName)));let result:any;if(a.mime==='text/csv')result=parseCSV(buffer.toString('utf8'),req.body.mapping||{});else{const text=await pdfText(buffer);result={items:parseStatementText(text),text,headers:[],issues:[]};}return {...result,items:matchItems(store.state(),req.body.accountId,result.items,req.body.tolerance??3)};});
 if(existsSync(resolve('dist')))await app.register(staticFiles,{root:resolve('dist'),wildcard:false,etag:false});
 app.setNotFoundHandler((req,reply)=>{if(req.url.startsWith('/api/'))return reply.code(404).send({error:'Not found.'});return existsSync(resolve('dist/index.html'))?reply.type('text/html').send(readFileSync(resolve('dist/index.html'))):reply.code(503).send('Run npm run build first.');});
 let ticking=false;const tick=async()=>{if(ticking||!store.meta('owner'))return;ticking=true;try{let s=store.state();const t=today(s.settings.timezone);for(const o of occurrences(s,t).filter(o=>!['POSTED','SKIPPED'].includes(o.status)).slice(0,100)){const b=s.accounts.find(a=>a.id===o.template.toAccountId);if(!s.settings.autoPost||o.rule.mode==='VARIABLE'||b?.type==='LOAN'&&!o.rule.autoSplit)continue;try{store.mutate({id:'schedule:'+o.id,epoch:s.epoch,collection:'events',action:'create',entityId:id(),deviceId:'scheduler',data:{...o.template,date:o.due,occurrenceId:o.id}});}catch(e){/* Invalid amounts or archived references remain visible for manual resolution. */}}
  s=store.state();for(const r of s.rules.filter(r=>r.status==='ACTIVE'&&(r.count||r.end))){const all=occurrences(s,r.end||dateAdd(t,36600)).filter(o=>o.ruleId===r.id);if(all.length&&all.every(o=>['POSTED','SKIPPED'].includes(o.status)))store.mutate({id:id(),epoch:s.epoch,collection:'rules',action:'update',entityId:r.id,baseVersion:r.version,deviceId:'scheduler',data:{...r,status:'ENDED'}});}
  const backup:any=store.db.prepare('SELECT * FROM backups ORDER BY created_at DESC LIMIT 1').get();const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:s.settings.timezone,hour:'numeric',hourCycle:'h23'}).format(new Date()));if(hour>=s.settings.backupHour&&(!backup||today(s.settings.timezone)!==new Intl.DateTimeFormat('en-CA',{timeZone:s.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(backup.created_at))))try{store.backup()}catch(e){store.setMeta('lastBackupError','Daily backup failed. Check persistent storage and create a manual backup.');}
  await copyCloudBackups(store);}finally{ticking=false;}};
 const timer=setInterval(()=>void tick().catch(()=>{}),60000);timer.unref();app.addHook('onClose',async()=>clearInterval(timer));return {app,store,tick};
}
if(import.meta.url===pathToFileURL(process.argv[1]||'').href){const {app,tick}=await createApp();await app.listen({host:process.env.HOST||'127.0.0.1',port:Number(process.env.PORT)||3080});console.log('Balancebook listening on port '+(process.env.PORT||3080));void tick();}
