import {blankState,id,today,dateAdd,buildEvent,applyMutation} from '../shared/domain';
import type {State,AccountType} from '../shared/types';
export function demoState():State{
 let s=blankState();s.settings.demo=true;s.settings.theme='dark';const t=today(s.settings.timezone),start=dateAdd(t,-95),now=new Date().toISOString();const base=()=>({id:id(),version:1,createdAt:now,updatedAt:now});
 for(const name of ['Groceries','Transport','Salary','Dining','Health','Utilities','Clothing','Subscriptions','Housing'])s.categories.push({...base(),name,active:true});
 for(const name of ['Walmart','Shell','Employer','Local Cafe','CVS','ISP','Shoe Store','Stream Co','Landlord'])s.payees.push({...base(),name,active:true});
 const names:[string,AccountType,number][]=[['Everyday Checking','CHECKING',345000],['Reserve Savings','SAVINGS',880000],['Cash Wallet','WALLET',20000],['Everyday Visa','CREDIT_CARD',-125000],['Rewards Mastercard','CREDIT_CARD',-260000],['Store Card','CREDIT_CARD',-50000],['Auto Loan','LOAN',-1450000],['Personal Loan','LOAN',-600000]];
 names.forEach(([name,type,opening],order)=>s.accounts.push({...base(),name,type,opening,trackingStart:start,institution:'Demo institution',archived:false,everUsed:false,order,details:type==='CREDIT_CARD'?{limit:500000,minimum:3500,closeDate:dateAdd(t,-12),dueDate:dateAdd(t,9)}:type==='LOAN'?{payment:45000,dueDay:15,apr:'6.5'}:{}}));
 const account=s.accounts[0].id,visa=s.accounts[3].id;const tx=(days:number,type:any,amount:number,payee:string,category:string,accountId=account,extra:any={})=>{const e=buildEvent(s,{id:id(),type,amount,date:dateAdd(t,days),accountId,payeeId:s.payees.find(p=>p.name===payee)?.id,categoryId:s.categories.find(c=>c.name===category)?.id,notes:'',...extra});s.events.push(e);return e;};
 for(let w=1;w<=10;w++){tx(-w*7,'EXPENSE',7000+w*317,'Walmart','Groceries');tx(-w*7+1,'EXPENSE',3500+w*51,'Shell','Transport',visa);tx(-w*7+2,'EXPENSE',1850,'Local Cafe','Dining');if(w%2===0)tx(-w*7+3,'INCOME',250000,'Employer','Salary');}
 tx(0,'EXPENSE',8642,'Walmart','Groceries');tx(0,'EXPENSE',4210,'Shell','Transport',visa);tx(-1,'INCOME',250000,'Employer','Salary');tx(-1,'TRANSFER',50000,'','',account,{toAccountId:s.accounts[1].id});tx(-2,'DEBT_PAYMENT',45000,'','',account,{toAccountId:s.accounts[6].id,principal:35000,interest:10000,subtype:'REGULAR'});tx(-2,'DEBT_PAYMENT',15000,'','',account,{toAccountId:visa});const shoes=tx(-5,'EXPENSE',8000,'Shoe Store','Clothing',visa);tx(-3,'REFUND',2000,'Shoe Store','Clothing',account,{refundOf:shoes.id});const voided=tx(-3,'EXPENSE',1499,'Stream Co','Subscriptions',visa);voided.status='VOIDED';tx(-4,'EXPENSE',6500,'ISP','Utilities');tx(-6,'ADJUSTMENT',500,'','',s.accounts[2].id,{direction:-1});
 for(let i=0;i<s.accounts.length;i++){const a=s.accounts[i];a.opening=names[i][2]-s.events.filter(e=>e.status==='ACTIVE').flatMap(e=>e.entries).filter(e=>e.accountId===a.id).reduce((v,e)=>v+e.amount,0);a.everUsed=s.events.some(e=>e.entries.some(l=>l.accountId===a.id));}
 const rule=(label:string,offset:number,template:any,unit:any='months',interval=1,mode:any='FIXED',count?:number)=>s.rules.push({...base(),label,start:dateAdd(t,offset),unit,interval,mode,status:'ACTIVE',notifyDays:3,autoSplit:false,count,template});
 rule('Rent',2,{type:'EXPENSE',accountId:account,amount:90000,payeeId:s.payees[8].id,categoryId:s.categories[8].id});rule('Auto payment',4,{type:'DEBT_PAYMENT',accountId:account,toAccountId:s.accounts[6].id,amount:45000,principal:35000,interest:10000,subtype:'REGULAR'});rule('Visa payment',5,{type:'DEBT_PAYMENT',accountId:account,toAccountId:visa,amount:15000});rule('Paycheck',6,{type:'INCOME',accountId:account,amount:250000,payeeId:s.payees[2].id,categoryId:s.categories[2].id},'weeks',2);rule('Electric bill',10,{type:'EXPENSE',accountId:account,payeeId:s.payees[5].id,categoryId:s.categories[5].id},'months',1,'VARIABLE');rule('Pay in 4',7,{type:'EXPENSE',accountId:account,amount:2500,payeeId:s.payees[6].id,categoryId:s.categories[6].id},'weeks',2,'FIXED',4);
 s.settings.forecastTarget='rule';s.settings.forecastRule=s.rules.find(r=>r.label==='Paycheck').id;
 s.revisions=s.events.map(e=>({id:id(),entityId:e.id,entityType:'events',action:'demo-fixture',before:null,after:e,at:now,actor:'Demo setup'}));return s;
}
