import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,existsSync,readFileSync,writeFileSync,readdirSync,unlinkSync,copyFileSync,statSync,renameSync} from 'node:fs';
import {resolve,join,basename} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import AdmZip from 'adm-zip';
import {applyMutation,blankState,DomainError,id} from '../shared/domain';
import type {State,Mutation} from '../shared/types';
export const hash=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
export class Store {
 db:DatabaseSync;dir:string;
 constructor(dir=process.env.DATA_DIR||'data'){this.dir=resolve(dir);for(const p of ['', 'files','backups','temp'])mkdirSync(join(this.dir,p),{recursive:true});this.db=new DatabaseSync(join(this.dir,'balancebook.sqlite'));this.db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=DELETE; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,date TEXT NOT NULL,status TEXT NOT NULL,occurrence_id TEXT UNIQUE,payload TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS ledger_entries(event_id TEXT REFERENCES events(id),account_id TEXT REFERENCES accounts(id),amount_cents INTEGER NOT NULL CHECK(typeof(amount_cents)='integer'),PRIMARY KEY(event_id,account_id));
 CREATE INDEX IF NOT EXISTS ledger_account ON ledger_entries(account_id,event_id); CREATE INDEX IF NOT EXISTS event_date ON events(date,status);
 CREATE TABLE IF NOT EXISTS records(kind TEXT NOT NULL,id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(kind,id));
 CREATE TABLE IF NOT EXISTS revisions(id TEXT PRIMARY KEY,entity_id TEXT NOT NULL,payload TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS immutable_revision_update BEFORE UPDATE ON revisions BEGIN SELECT RAISE(ABORT,'Audit revisions are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS immutable_revision_delete BEFORE DELETE ON revisions BEGIN SELECT RAISE(ABORT,'Audit revisions are immutable'); END;
 CREATE INDEX IF NOT EXISTS revision_entity ON revisions(entity_id);
 CREATE TABLE IF NOT EXISTS applied_mutations(id TEXT PRIMARY KEY,result TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,last_seen INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS backups(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,filename TEXT NOT NULL,checksum TEXT NOT NULL,size INTEGER NOT NULL,cloud_status TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS pushes(endpoint TEXT PRIMARY KEY,payload TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS notices(id TEXT PRIMARY KEY,at TEXT NOT NULL);
 INSERT OR IGNORE INTO schema_migrations VALUES(1,datetime('now'));`);if(!this.meta('epoch'))this.save(blankState());}
 meta(k:string):any{const row:any=this.db.prepare('SELECT value FROM meta WHERE key=?').get(k);return row?JSON.parse(row.value):null}
 setMeta(k:string,v:any){this.db.prepare('INSERT INTO meta VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,JSON.stringify(v));}
 transaction<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const r=fn();this.db.exec('COMMIT');return r}catch(e){this.db.exec('ROLLBACK');throw e}}
 state():State{const s=blankState();s.epoch=this.meta('epoch');s.settings=this.meta('settings');s.accounts=(this.db.prepare('SELECT payload FROM accounts').all() as any[]).map(r=>JSON.parse(r.payload));s.events=(this.db.prepare('SELECT payload FROM events ORDER BY date DESC').all() as any[]).map(r=>JSON.parse(r.payload));s.revisions=(this.db.prepare('SELECT payload FROM revisions ORDER BY rowid').all() as any[]).map(r=>JSON.parse(r.payload));for(const r of this.db.prepare('SELECT kind,payload FROM records').all() as any[])if(Array.isArray(s[r.kind]))s[r.kind].push(JSON.parse(r.payload));return s;}
 save(s:State){this.setMeta('epoch',s.epoch);this.setMeta('settings',s.settings);const a=this.db.prepare('INSERT INTO accounts VALUES(?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload');for(const v of s.accounts)a.run(v.id,JSON.stringify(v));const e=this.db.prepare('INSERT INTO events VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET date=excluded.date,status=excluded.status,occurrence_id=excluded.occurrence_id,payload=excluded.payload');const previousEvents=new Map((this.db.prepare('SELECT id,payload FROM events').all() as any[]).map(r=>[r.id,r.payload]));for(const v of s.events){if(previousEvents.get(v.id)===JSON.stringify(v))continue;e.run(v.id,v.date,v.status,v.occurrenceId||null,JSON.stringify(v));this.db.prepare('DELETE FROM ledger_entries WHERE event_id=?').run(v.id);for(const l of v.entries)this.db.prepare('INSERT INTO ledger_entries VALUES(?,?,?)').run(v.id,l.accountId,l.amount);}const rec=this.db.prepare('INSERT INTO records VALUES(?,?,?) ON CONFLICT(kind,id) DO UPDATE SET payload=excluded.payload');for(const k of ['categories','payees','rules','occurrences','attachments','reconciliations','checkpoints']){for(const v of s[k])rec.run(k,v.id,JSON.stringify(v));const allowed=new Set(s[k].map(v=>v.id));for(const v of this.db.prepare('SELECT id FROM records WHERE kind=?').all(k) as any[])if(!allowed.has(v.id))this.db.prepare('DELETE FROM records WHERE kind=? AND id=?').run(k,v.id);}for(const r of s.revisions)this.db.prepare('INSERT OR IGNORE INTO revisions VALUES(?,?,?)').run(r.id,r.entityId,JSON.stringify(r));}
 mutate(m:Mutation){return this.transaction(()=>{const old:any=this.db.prepare('SELECT result FROM applied_mutations WHERE id=?').get(m.id);if(old)return JSON.parse(old.result);const s=this.state();
  if(m.collection==='events'&&m.action==='create'&&m.data.occurrenceId){const existing=s.events.find(e=>e.occurrenceId===m.data.occurrenceId);if(existing){if(['type','date','amount','accountId','toAccountId','notes',...(['EXPENSE','INCOME','REFUND'].includes(existing.type)?['payeeId','categoryId']:[]),...(existing.principal!==undefined?['principal','interest','subtype']:[])].some(k=>(existing[k]??'')!==(m.data[k]??(k==='subtype'?'REGULAR':''))))throw new DomainError('This occurrence posted with different values. Review the server transaction.',409,{server:existing,local:m.data,mutation:m});const result={entity:existing,duplicate:true};this.db.prepare('INSERT INTO applied_mutations VALUES(?,?)').run(m.id,JSON.stringify(result));return result;}}
  const n=applyMutation(s,m);this.save(n);const result={entity:m.collection==='settings'?n.settings:n[m.collection].find(e=>e.id===m.entityId)};this.db.prepare('INSERT INTO applied_mutations VALUES(?,?)').run(m.id,JSON.stringify(result));return result;});}
 backup(){const bid=randomUUID(),snapshot=join(this.dir,'temp',bid+'.sqlite');this.db.exec(`VACUUM INTO '${snapshot.replaceAll("'","''")}'`);const zip=new AdmZip();const db=readFileSync(snapshot);zip.addFile('database.sqlite',db);const files:Record<string,string>={'database.sqlite':hash(db)};for(const name of readdirSync(join(this.dir,'files'))){const b=readFileSync(join(this.dir,'files',name));zip.addFile('files/'+name,b);files['files/'+name]=hash(b);}const s=this.state();const portable=Buffer.from(JSON.stringify(s,null,2));zip.addFile('export.json',portable);files['export.json']=hash(portable);const csv=['date,type,payee,category,account,amount_cents,status',...s.events.map(e=>[e.date,e.type,e.payee,e.category,e.accountId,e.amount,e.status].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\r\n');zip.addFile('transactions.csv',Buffer.from(csv));files['transactions.csv']=hash(csv);zip.addFile('manifest.json',Buffer.from(JSON.stringify({version:1,createdAt:new Date().toISOString(),files},null,2)));const filename=`balancebook-backup-${new Date().toISOString().replace(/[:.]/g,'-')}-${bid.slice(0,8)}.zip`;const out=zip.toBuffer();writeFileSync(join(this.dir,'backups',filename),out);unlinkSync(snapshot);this.db.prepare('INSERT INTO backups VALUES(?,?,?,?,?,?)').run(bid,new Date().toISOString(),filename,hash(out),out.length,process.env.RCLONE_REMOTE?'waiting':'not-configured');this.setMeta('lastBackupError',null);const rows:any[]=this.db.prepare('SELECT * FROM backups ORDER BY created_at DESC').all();for(const row of rows.slice(s.settings.retention)){const p=join(this.dir,'backups',basename(row.filename));if(existsSync(p))unlinkSync(p);this.db.prepare('DELETE FROM backups WHERE id=?').run(row.id);}return {id:bid,filename};}
 restore(buffer:Buffer){const zip=new AdmZip(buffer);const manifestEntry=zip.getEntry('manifest.json');if(!manifestEntry)throw new DomainError('Missing backup manifest.');const manifest=JSON.parse(manifestEntry.getData().toString());if(manifest.version!==1)throw new DomainError('Unsupported backup version.');if(!manifest.files?.['database.sqlite'])throw new DomainError('Missing database checksum.');for(const [name,checksum] of Object.entries(manifest.files)){if(name!=='database.sqlite'&&name!=='export.json'&&name!=='transactions.csv'&&!/^files\/[a-zA-Z0-9.-]+$/.test(name))throw new DomainError('Unsafe archive entry.');const e=zip.getEntry(name);if(!e||hash(e.getData())!==checksum)throw new DomainError('Backup checksum mismatch: '+name);}
  const test=join(this.dir,'temp','restore-'+randomUUID()+'.sqlite');writeFileSync(test,zip.readFile('database.sqlite'));const check=new DatabaseSync(test);const integrity:any=check.prepare('PRAGMA integrity_check').get();const owner:any=check.prepare("SELECT value FROM meta WHERE key='owner'").get();const candidateEpoch:any=check.prepare("SELECT value FROM meta WHERE key='epoch'").get();if(Object.values(integrity)[0]!=='ok'||!owner||!candidateEpoch){check.close();unlinkSync(test);throw new DomainError('Backup database is not a valid initialized Balancebook ledger.');}check.close();const safety=this.backup();
  // New files are immutable and keyed by content hash. Existing files remain for safety recovery.
  for(const name of Object.keys(manifest.files).filter(k=>k.startsWith('files/')))writeFileSync(join(this.dir,'files',basename(name)),zip.readFile(name));
  const current=join(this.dir,'balancebook.sqlite'),rollback=join(this.dir,'temp','previous-'+randomUUID()+'.sqlite');this.db.close();renameSync(current,rollback);try{copyFileSync(test,current);this.db=new DatabaseSync(current);}catch(error){if(existsSync(current))unlinkSync(current);renameSync(rollback,current);this.db=new DatabaseSync(current);this.db.exec('PRAGMA foreign_keys=ON');throw error;}unlinkSync(rollback);unlinkSync(test);this.db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=DELETE; DELETE FROM sessions; DELETE FROM applied_mutations;');this.setMeta('epoch',id());for(const row of this.db.prepare('SELECT id,filename FROM backups').all() as any[])if(!existsSync(join(this.dir,'backups',basename(row.filename))))this.db.prepare('DELETE FROM backups WHERE id=?').run(row.id);const safetyPath=join(this.dir,'backups',safety.filename);const safetyBytes=readFileSync(safetyPath);this.db.prepare('INSERT OR IGNORE INTO backups VALUES(?,?,?,?,?,?)').run(safety.id,new Date().toISOString(),safety.filename,hash(safetyBytes),safetyBytes.length,'not-configured');return {safety,requiresLogin:true};}
 close(){this.db.close()}
}
