import React,{useEffect,useState} from 'react';
import {cents,money} from '../shared/domain';
import {api} from './ledger';
import {Panel,Button,Select,Money,Field} from './components';
import {BankConnections} from './BankConnections';

export function BankAttention({l}:any){
 const [busy,setBusy]=useState(false);const rows=l.state.events.filter(e=>e.status==='ACTIVE'&&e.bank?.attention);
 async function resolve(eventId:string,manualId?:string){setBusy(true);try{await api('/plaid/match',{eventId,manualId});await l.sync();}catch(e:any){l.setError(e.message)}finally{setBusy(false)}}
 return <><div className="toolbar"><BankConnections l={l}/></div>{rows.length>0&&<Panel title={`Needs attention (${rows.length})`}>{rows.map(e=><div key={e.id} className="panel"><strong>{e.payee} · {e.date} · <Money value={e.amount}/></strong><p>{e.bank.attention}</p>{e.principal!==undefined&&e.bank.refs?.length>0&&<SplitCorrection l={l} event={e}/>}{(e.bank.candidates||[]).map(id=>{const m=l.state.events.find(v=>v.id===id&&v.status==='ACTIVE');return m&&<Button key={id} disabled={busy||!l.online} onClick={()=>resolve(e.id,id)}>Match {m.payee} · {m.date} · <Money value={m.amount}/></Button>})}{e.bank.candidates?.length>0&&<Button disabled={busy||!l.online} onClick={()=>resolve(e.id)}>Keep as separate transactions</Button>}</div>)}</Panel>}</>;
}

export function BankRecurring({l}:any){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[choices,setChoices]=useState<any>({});
 const load=()=>api('/plaid/recurring').then(setData).catch(e=>setError(e.message));useEffect(()=>{if(l.online)void load()},[l.online]);
 async function link(item:any,stream:any){setBusy(true);setError('');try{await api('/plaid/recurring/link',{itemId:item.itemId,streamId:stream.stream_id,...(choices[stream.stream_id]?{ruleId:choices[stream.stream_id]}:{})});await l.sync();await load();l.setNotice('Recurring stream linked. Your schedule controls the dates and amounts.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!data?.items?.length)return error?<p role="alert">{error}</p>:null;
 return <Panel title="Detected by your bank" action={<Button disabled={busy||!l.online} onClick={load}>Reload streams</Button>}><p>Link a stream to an existing rule to preserve its dates, amounts and payment splits, or create a rule from the bank’s prediction. Bank activity confirms payments automatically.</p>{error&&<p role="alert" className="banner error">{error}</p>}{data.items.map(item=><React.Fragment key={item.itemId}>{item.error&&<p role="alert">Recurring data unavailable: {item.error}</p>}{!item.streams.length&&<p>No recurring streams available yet. Sync your connection after Plaid finishes processing history.</p>}{item.streams.filter(v=>v.is_active).map(v=>{const linked=l.state.rules.find(r=>r.status==='ACTIVE'&&r.plaid?.itemId===item.itemId&&r.plaid.streamId===v.stream_id);return <div className="panel bank-stream" key={v.stream_id}><strong>{v.merchant_name||v.description}</strong><p>{l.state.accounts.find(a=>a.id===v.accountId)?.name} · {v.frequency.toLowerCase().replaceAll('_',' ')} · <Money value={Math.round(Math.abs(v.last_amount?.amount||v.average_amount?.amount||0)*100)}/> · Next {v.predicted_next_date||'not predicted'}</p>{linked?<p>Linked to {linked.label}</p>:<div className="toolbar"><Select value={choices[v.stream_id]||''} onChange={e=>setChoices({...choices,[v.stream_id]:e.target.value})} options={[{value:'',label:'Create from bank prediction'},...l.state.rules.filter(r=>!r.plaid&&r.template.accountId===v.accountId&&r.status==='ACTIVE').map(r=>({value:r.id,label:'Link to '+r.label}))]}/><Button disabled={busy||!l.online||!choices[v.stream_id]&&(!v.predicted_next_date||!['WEEKLY','BIWEEKLY','MONTHLY','ANNUALLY'].includes(v.frequency))} onClick={()=>link(item,v)}>Use this stream</Button>{!choices[v.stream_id]&&(!v.predicted_next_date||!['WEEKLY','BIWEEKLY','MONTHLY','ANNUALLY'].includes(v.frequency))&&<small>Create a rule with your payment dates above, then select it here to link this stream.</small>}</div>}</div>})}</React.Fragment>)}</Panel>;
}

function SplitCorrection({l,event:e}:any){const [principal,setPrincipal]=useState((e.principal/100).toFixed(2)),[interest,setInterest]=useState((e.interest/100).toFixed(2)),[busy,setBusy]=useState(false);const total=-(e.bank.refs.find(r=>r.accountId===e.accountId)?.amount||0);return <form onSubmit={async ev=>{ev.preventDefault();setBusy(true);try{await api('/plaid/payment-split',{eventId:e.id,principal:cents(principal),interest:cents(interest)});await l.sync();}catch(err:any){l.setError(err.message)}finally{setBusy(false)}}}><p>Bank payment: {money(total)}</p><div className="form-row"><Field label="Principal"><input inputMode="decimal" value={principal} onChange={v=>setPrincipal(v.target.value)}/></Field><Field label="Interest"><input inputMode="decimal" value={interest} onChange={v=>setInterest(v.target.value)}/></Field></div><Button type="submit" disabled={busy||!l.online}>Update payment split</Button></form>}
