import {useDialogs} from './dialogs';
import {useEffect,useRef,useState} from 'react';
import {openDB} from 'idb';
import {applyMutation,id,DomainError} from '../shared/domain';
import type {State,Mutation,Collection} from '../shared/types';
const database=()=>openDB('balancebook-vault',1,{upgrade(db){db.createObjectStore('vault')}});
const encoder=new TextEncoder(),decoder=new TextDecoder();
const b64=(a:Uint8Array)=>{let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s)};
const un64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function keyFor(password:string,salt:Uint8Array){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt as BufferSource,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function api(path:string,body?:any,method?:string){const isForm=body instanceof FormData;const response=await fetch('/api/v1'+path,{method:method||(body===undefined?'GET':'POST'),headers:body===undefined?{}:{'x-requested-with':'balancebook',...(!isForm?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:isForm?body:JSON.stringify(body)});const data=await response.json();if(!response.ok){const error:any=new Error(data.error||'Request failed');error.status=response.status;error.details=data.details;throw error;}return data;}
interface Payload {state:State;pending:Mutation[];files:any[];draft:any;email:string}
export function useLedger(){
 const dialogs=useDialogs();
 const [state,setState]=useState<State|null>(null),[locked,setLocked]=useState(true),[online,setOnline]=useState(navigator.onLine),[syncing,setSyncing]=useState(false),[pending,setPending]=useState<Mutation[]>([]),[conflict,setConflict]=useState<any>(null),[backups,setBackups]=useState<any[]>([]),[backupError,setBackupError]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[draft,setDraft]=useState<any>(null),[remembered,setRemembered]=useState('');
 const vault=useRef<{key:CryptoKey;salt:Uint8Array}|null>(null),payload=useRef<Payload|null>(null),writing=useRef(Promise.resolve()),busy=useRef(false),activity=useRef(Date.now());
 const device=useRef(localStorage.getItem('bb-device')||id());useEffect(()=>{localStorage.setItem('bb-device',device.current);setRemembered(localStorage.getItem('bb-email')||'');const fn=()=>setOnline(navigator.onLine);window.addEventListener('online',fn);window.addEventListener('offline',fn);return()=>{window.removeEventListener('online',fn);window.removeEventListener('offline',fn)}},[]);
 const persist=()=>{const v=vault.current,p=payload.current;if(!v||!p)return Promise.resolve();const raw=JSON.stringify(p);writing.current=writing.current.catch(()=>{}).then(async()=>{const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},v.key,encoder.encode(raw));await (await database()).put('vault',{email:p.email,salt:b64(v.salt),iv:b64(iv),data:b64(new Uint8Array(data))},'data')}).catch(()=>setError('Local storage is full or unavailable. Keep this window open and export pending changes.'));return writing.current;};
 const publish=(p:Payload)=>{payload.current=p;setState(p.state);setPending([...p.pending]);setDraft(p.draft);void persist();};
 const lock=()=>{dialogs.dismissAll();void persist();void api('/logout',{}).catch(()=>{});vault.current=null;payload.current=null;setState(null);setDraft(null);setPending([]);setConflict(null);setLocked(true);};
 useEffect(()=>{if(locked)return;const touch=()=>{activity.current=Date.now()};const interval=setInterval(()=>{if(Date.now()-activity.current>(payload.current?.state.settings.timeout||30)*60000)lock()},5000);window.addEventListener('pointerdown',touch);window.addEventListener('keydown',touch);return()=>{clearInterval(interval);window.removeEventListener('pointerdown',touch);window.removeEventListener('keydown',touch)}},[locked]);
 async function login(email:string,password:string,setup=false,demo=false,remember=false){setError('');let cached:Payload=null,key:CryptoKey,salt:Uint8Array;const stored=await (await database()).get('vault','data');if(stored&&stored.email===email.toLowerCase()){salt=un64(stored.salt);key=await keyFor(password,salt);try{cached=JSON.parse(decoder.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(stored.iv)},key,un64(stored.data))))}catch{/* Changed server password needs a fresh local vault after online authentication. */}}
  let remote:any=null;try{remote=await api(setup?'/setup':'/login',{email,password,demo})}catch(e:any){if(e.status||!cached)throw e;setOnline(false)}
  if(!cached&&!remote)throw new Error('Offline login needs a prior successful login on this device.');if(!cached){salt=crypto.getRandomValues(new Uint8Array(16));key=await keyFor(password,salt);}vault.current={key,salt};const p=cached?.pending.length||cached?.files.length?cached:{state:remote?.state||cached.state,pending:[],files:[],draft:cached?.draft||null,email:email.toLowerCase()};publish(p);setLocked(false);activity.current=Date.now();if(remember)localStorage.setItem('bb-email',email);else localStorage.removeItem('bb-email');if(remote){setOnline(true);setTimeout(()=>void sync(),20);}
 }
 async function sync(){if(busy.current||!payload.current||!navigator.onLine)return;busy.current=true;setSyncing(true);try{
  const remote=await api('/state');setBackups(remote.backups);setBackupError(remote.backupError||'');let p=payload.current;if(!p)return;if(p.state.epoch!==remote.state.epoch&&(p.pending.length||p.files.length)){setConflict({epoch:true,message:'The server was restored. Export your pending changes before refreshing this device.'});return;}
  const activeVault=vault.current;
  while(payload.current?.pending.length&&vault.current===activeVault){const m=payload.current.pending[0];try{await api('/mutations',m);if(!payload.current||vault.current!==activeVault)return;publish({...payload.current,pending:payload.current.pending.filter(q=>q.id!==m.id)});await persist();}catch(e:any){if(!payload.current||vault.current!==activeVault)return;if(e.status===409){setConflict({...e.details,mutation:m});return;}if(e.status===400){setConflict({mutation:m,server:null,local:m.data,message:e.message,validation:true});return;}throw e;}}
  while(payload.current?.files.length&&vault.current===activeVault){const f=payload.current.files[0];const form=new FormData();form.append('entityId',f.entityId);form.append('kind','transaction');form.append('clientId',f.id);form.append('file',new Blob([un64(f.data)],{type:f.mime}),f.name);await api('/files',form);if(!payload.current||vault.current!==activeVault)return;publish({...payload.current,files:payload.current.files.filter(x=>x.id!==f.id)});await persist();}
  const fresh=await api('/state');if(payload.current&&vault.current===activeVault&&!payload.current.pending.length&&!payload.current.files.length)publish({...payload.current,state:fresh.state});setOnline(true);setConflict(null);
 }catch(e:any){if(e.status===401){setError('Your server session expired. Lock and log in to sync; your local changes are saved.');}else if(!e.status)setOnline(false);else setError(e.message);}finally{busy.current=false;setSyncing(false);}}
 useEffect(()=>{if(!locked){void sync();const t=setInterval(()=>void sync(),30000);return()=>clearInterval(t)}},[locked,online]);
 async function mutate(collection:Collection|'settings',action:string,data:any,entityId?:string,extra:any={}){const p=payload.current;if(!p)throw new Error('Log in first.');const eid=collection==='settings'?'settings':entityId||data.id||id();const before=collection==='settings'?p.state.settings:p.state[collection].find(e=>e.id===eid);const m:Mutation={id:id(),epoch:p.state.epoch,collection,action,entityId:eid,baseVersion:before?(before.version||0):undefined,data,deviceId:device.current,...extra};let next:State;try{next=applyMutation(p.state,m)}catch(e:any){if(e.status===409)setConflict({...e.details,mutation:m});throw e;}publish({...p,state:next,pending:[...p.pending,m]});await persist();void sync();return eid;}
 async function queueFile(entityId:string,file:File){if(file.size>25*1024*1024)throw new Error('Attachments must be 25 MB or smaller.');const activeVault=vault.current;const f={id:id(),entityId,name:file.name,mime:file.type,data:b64(new Uint8Array(await file.arrayBuffer()))};const p=payload.current;if(!p||vault.current!==activeVault)return;publish({...p,files:[...p.files,f]});await persist();void sync();}
 function saveDraft(d:any){if(payload.current)publish({...payload.current,draft:d});}
 async function resolveConflict(choice:string,merged?:any){const p=payload.current;if(!p)return;if(conflict.epoch){if(!await dialogs.confirm('Discard all unsynced transactions and files on this device and load the restored server ledger?'))return;p.pending=[];p.files=[];p.state=(await api('/state')).state;}else{const old=conflict.mutation;if(choice==='server')await api('/conflict-resolution',{entityId:old.entityId,collection:old.collection,local:old.data});p.pending=p.pending.filter(m=>m.id!==old.id);if(choice==='local'){const target=conflict.server;p.pending.unshift({...old,id:id(),entityId:target?.id||old.entityId,action:target?'update':'create',baseVersion:old.collection==='settings'?(target?.version||0):target?.version,data:merged||old.data,resolution:'Owner chose local or merged values'});}}publish(p);setConflict(null);await sync();}
 async function logout(){if((payload.current?.pending.length||payload.current?.files.length)&&!await dialogs.confirm('Unsynced changes will be removed from this device. Export them first if needed. Log out anyway?'))return;dialogs.dismissAll();try{await api('/logout',{})}catch{}await writing.current;await (await database()).delete('vault','data');vault.current=null;payload.current=null;setState(null);setLocked(true);setPending([]);}
 function exportPending(){const raw=JSON.stringify({pending:payload.current?.pending,files:payload.current?.files},null,2);const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='balancebook-unsynced.json';a.click();URL.revokeObjectURL(url);}
 return {confirm:dialogs.confirm,prompt:dialogs.prompt,state,locked,online,syncing,pending,conflict,backups,backupError,error,setError,notice,setNotice,draft,saveDraft,remembered,login,lock,logout,mutate,queueFile,sync,resolveConflict,exportPending};
}
export type Ledger=ReturnType<typeof useLedger>;
