import React,{useState} from 'react';
import {Modal,Button,Field,ComboBox,Money} from './components';
import {suggestMerchant,learnedAliases} from '../shared/merchants';
export function ReplaceAdjustment({l,session,item,adjustment,onClose}:any){
 const [payee,setPayee]=useState(suggestMerchant(item.description,l.state.payees,learnedAliases(l.state),session.accountId).name||item.description||''),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const remaining=adjustment?adjustment.amount+item.amount:0;
 async function save(){setBusy(true);setError('');try{if(!adjustment){await l.mutate('reconciliations','add-transaction',{rowId:item.id,payee,category},session.id,{baseVersion:session.version});l.setNotice('Transaction added and statement row matched.');onClose();return;}await l.mutate('reconciliations','replace-adjustment',{rowId:item.id,adjustmentId:adjustment.id,adjustmentVersion:adjustment.version,payee,category},session.id,{baseVersion:session.version});l.setNotice('Expense created and adjustment reduced together. Account balance unchanged.');onClose();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <Modal title={adjustment?'Replace part of adjustment':'Add transaction'} onClose={()=>{if(!busy)onClose()}}><>{adjustment?<><p>Create this purchase by reducing the existing adjustment by the same amount.</p><table><tbody><tr><th>New expense · {item.date}</th><td><Money value={-item.amount}/></td></tr><tr><th>Current adjustment</th><td><Money value={adjustment.amount}/></td></tr><tr><th>Remaining adjustment</th><td><Money value={remaining}/>{remaining===0&&<small>The adjustment will be voided, with history retained.</small>}</td></tr><tr><th>Account balance change</th><td><Money value={0}/></td></tr></tbody></table><p>The expense uses the bank transaction date; balances between that date and the adjustment date may change.</p></>:<><p>Add this transaction and match the statement row in one step.</p><table><tbody><tr><th>Account</th><td>{l.state.accounts.find(a=>a.id===session.accountId)?.name}</td></tr><tr><th>Date</th><td>{item.date}</td></tr><tr><th>{item.amount<0?'Expense':'Income'}</th><td><Money value={Math.abs(item.amount)}/></td></tr><tr><th>Account balance change</th><td><Money value={item.amount}/></td></tr></tbody></table></>}</><Field label="Payee" required><ComboBox options={l.state.payees.filter(p=>p.active).map(p=>p.name)} value={payee} onChange={e=>setPayee(e.target.value)}/></Field><Field label="Category" required><ComboBox options={l.state.categories.filter(p=>p.active).map(p=>p.name)} value={category} onChange={e=>setCategory(e.target.value)}/></Field>{error&&<div role="alert" className="banner error">{error}</div>}<div className="form-actions"><Button disabled={busy} onClick={onClose}>Cancel</Button><Button primary disabled={busy||!payee.trim()||!category.trim()||remaining<0} onClick={save}>{busy?'Saving…':adjustment?'Create expense and reduce adjustment':'Add transaction'}</Button></div></Modal>;
}
