import React,{useState} from 'react';
import {Modal,Button,Field,ComboBox,Money} from './components';
import {suggestMerchant} from '../shared/merchants';
export function ReplaceAdjustment({l,session,item,adjustment,onClose}:any){
 const [payee,setPayee]=useState(suggestMerchant(item.description,l.state.payees).name),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const remaining=adjustment.amount+item.amount;
 async function save(){setBusy(true);setError('');try{await l.mutate('reconciliations','replace-adjustment',{rowId:item.id,adjustmentId:adjustment.id,adjustmentVersion:adjustment.version,payee,category},session.id,{baseVersion:session.version});l.setNotice('Expense created and adjustment reduced together. Account balance unchanged.');onClose();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <Modal title="Replace part of adjustment" onClose={()=>{if(!busy)onClose()}}><p>Create this purchase by reducing the existing adjustment by the same amount.</p><table><tbody><tr><th>New expense · {item.date}</th><td><Money value={-item.amount}/></td></tr><tr><th>Current adjustment</th><td><Money value={adjustment.amount}/></td></tr><tr><th>Remaining adjustment</th><td><Money value={remaining}/>{remaining===0&&<small>The adjustment will be voided, with history retained.</small>}</td></tr><tr><th>Account balance change</th><td><Money value={0}/></td></tr></tbody></table><p>The expense uses the bank transaction date; balances between that date and the adjustment date may change.</p><Field label="Payee" required><ComboBox options={l.state.payees.filter(p=>p.active).map(p=>p.name)} value={payee} onChange={e=>setPayee(e.target.value)}/></Field><Field label="Category" required><ComboBox options={l.state.categories.filter(p=>p.active).map(p=>p.name)} value={category} onChange={e=>setCategory(e.target.value)}/></Field>{error&&<div role="alert" className="banner error">{error}</div>}<div className="form-actions"><Button disabled={busy} onClick={onClose}>Cancel</Button><Button primary disabled={busy||!payee.trim()||!category.trim()||remaining<0} onClick={save}>{busy?'Saving…':'Create expense and reduce adjustment'}</Button></div></Modal>;
}
