import React,{useState,useEffect} from 'react';
import {Search,SlidersHorizontal,X} from 'lucide-react';
import {Title,Button,Select,Field,Modal} from './components';
import {TransactionTable} from './App';
import {money} from '../shared/domain';
import {eventTypes} from '../shared/types';
const defaults={account:'',category:'',payee:'',type:'',status:'',from:'',to:''};
export function Transactions({l,openTx,onImport}:any){
 const s=l.state,[search,setSearch]=useState(''),[filters,setFilters]=useState({...defaults}),[draft,setDraft]=useState({...defaults}),[filterOpen,setFilterOpen]=useState(false),[sort,setSort]=useState('date'),[page,setPage]=useState(0),[error,setError]=useState('');
 const {account,category,payee,type,status,from,to}=filters;
 const events=s.events.filter(e=>(!account||e.accountId===account||e.entries.some(entry=>entry.accountId===account))&&(!category||e.categoryId===category)&&(!payee||e.payeeId===payee)&&(!type||e.type===type)&&(!status||e.status===status)&&(!from||e.date>=from)&&(!to||e.date<=to)&&(!search||[e.payee,e.category,e.notes,money(e.amount),String(e.amount/100)].join(' ').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='amount'?b.amount-a.amount:sort==='payee'?a.payee.localeCompare(b.payee):sort==='category'?a.category.localeCompare(b.category):b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 useEffect(()=>setPage(0),[search,filters,sort]);
 const lastPage=Math.max(0,Math.ceil(events.length/30)-1),visiblePage=Math.min(page,lastPage);
 const options=(rows:any[],all:string)=>[{value:'',label:all},...rows.map(r=>({value:r.id,label:r.name+(!r.active&&r.active!==undefined?' (hidden)':r.archived?' (archived)':'')}))];
 const filterLabels={account:s.accounts.find(a=>a.id===account)?.name,category:s.categories.find(c=>c.id===category)?.name,payee:s.payees.find(p=>p.id===payee)?.name,type:eventTypes[type],status:status==='VOIDED'?'Voided':'Active',from:'From '+from,to:'To '+to};
 const active=Object.entries(filters).filter(([,value])=>value),set=(key:string,value:string)=>setDraft({...draft,[key]:value});
 return <><Title title="Transactions" sub="Combined ledger · All accounts" actions={<Button onClick={onImport}>Import CSV</Button>}/>
  <div className="transaction-toolbar"><div className="search"><Search size={16}/><input autoComplete="off" aria-label="Search transactions" placeholder="Search payee, category, notes, or amount" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button className={active.length?'active':''} onClick={()=>{setDraft({...filters});setError('');setFilterOpen(true)}}><SlidersHorizontal size={15}/> Filters{active.length>0&&<span className="filter-count">{active.length}</span>}</Button><Select aria-label="Sort transactions" value={sort} onChange={e=>setSort(e.target.value)} options={[{value:'date',label:'Date · newest first'},{value:'amount',label:'Amount · largest first'},{value:'payee',label:'Payee · A–Z'},{value:'category',label:'Category · A–Z'}]}/></div>
  {active.length>0&&<div className="active-filters" aria-label="Active filters">{active.map(([key])=><Button key={key} aria-label={'Remove '+key+' filter'} onClick={()=>setFilters({...filters,[key]:''})}>{filterLabels[key]}<X size={12}/></Button>)}<button className="link" onClick={()=>setFilters({...defaults})}>Clear filters</button></div>}
  <div className="panel"><TransactionTable events={events.slice(visiblePage*30,visiblePage*30+30)} state={s} onSelect={openTx}/></div><div className="table-footer"><span>{events.length?`${visiblePage*30+1}–${Math.min(visiblePage*30+30,events.length)} of ${events.length}`:'0 transactions'}</span><span>Select a transaction to inspect details.</span><div><Button disabled={visiblePage===0} onClick={()=>setPage(visiblePage-1)}>Previous</Button><Button disabled={visiblePage>=lastPage} onClick={()=>setPage(visiblePage+1)}>Next</Button></div></div>
  {filterOpen&&<Modal title="Filter transactions" onClose={()=>setFilterOpen(false)}><form autoComplete="off" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),next={...draft,from:String(data.get('from')||''),to:String(data.get('to')||'')};setDraft(next);if(next.from&&next.to&&next.from>next.to){setError('End date must be on or after the start date.');return;}setFilters(next);setFilterOpen(false)}}><div className="filter-form-grid"><Field label="Account"><Select aria-label="Account filter" value={draft.account} onChange={e=>set('account',e.target.value)} options={options(s.accounts,'All accounts')}/></Field><Field label="Type"><Select aria-label="Type filter" value={draft.type} onChange={e=>set('type',e.target.value)} options={[{value:'',label:'All types'},...Object.entries(eventTypes).map(([value,label])=>({value,label}))]}/></Field><Field label="Start date"><input autoComplete="off" name="from" type="date" value={draft.from} onChange={e=>set('from',e.target.value)}/></Field><Field label="End date"><input autoComplete="off" name="to" type="date" value={draft.to} onChange={e=>set('to',e.target.value)}/></Field><Field label="Category"><Select aria-label="Category filter" value={draft.category} onChange={e=>set('category',e.target.value)} options={options(s.categories,'All categories')}/></Field><Field label="Payee"><Select aria-label="Payee filter" value={draft.payee} onChange={e=>set('payee',e.target.value)} options={options(s.payees,'All payees')}/></Field><Field label="Status"><Select aria-label="Status filter" value={draft.status} onChange={e=>set('status',e.target.value)} options={[{value:'',label:'Active + Voided'},{value:'ACTIVE',label:'Active'},{value:'VOIDED',label:'Voided'}]}/></Field></div>{error&&<div className="banner error" role="alert">{error}</div>}<div className="form-actions"><Button type="button" onClick={()=>{setDraft({...defaults});setError('')}}>Reset filters</Button><Button type="button" onClick={()=>setFilterOpen(false)}>Cancel</Button><Button type="submit" primary>Apply filters</Button></div></form></Modal>}
 </>;
}
